# Generated by Django 6.0.6 on 2026-06-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_genre_language_rename_booked_at_booking_booking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('LOCKED', 'Locked'), ('BOOKED', 'Booked')], default='AVAILABLE', max_length=10),
        ),
    ]
