# Generated by Django 6.0.6 on 2026-06-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seat_locked_until_alter_seat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
