"""
Django settings for bookmyseat project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&e)^!73i3(24&1x7_&=&^7nxa-a)_69+=f3+retlyq1&(034m7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# MUST be '*' so Render can host it
ALLOWED_HOSTS = ['*'] 


# Application definition
INSTALLED_APPS = [
    'daphne',  # MUST be at the very top for Channels/WebSockets
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'channels', # Required for real-time WebSockets
    
    # Register your app here
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Required for Render static files (CSS/JS)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bookmyseat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookmyseat.wsgi.application'
ASGI_APPLICATION = 'bookmyseat.asgi.application' # Required to route WebSockets


# Real-Time WebSocket Configuration
# In-Memory Channel Layer for Render Free Tier (Replaces Redis)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Tells Render where to build static files


# Trust Render's secure HTTPS URLs
# IMPORTANT: Once you know your exact Render link, replace 'your-app-name' below
CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com', 
    'https://akhils-movie-app.onrender.com' # Use your exact new link here
]

INSTALLED_APPS += ['debug_toolbar']
MIDDLEWARE = ['debug_toolbar.middleware.DebugToolbarMiddleware'] + MIDDLEWARE
INTERNAL_IPS = ['127.0.0.1']

# --- CELERY & REDIS CONFIGURATION ---
# For local Windows development, we will point this to a local Redis server.
# When we deploy to Render, we will change this to Render's internal Redis URL.
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# We will configure the actual Email SMTP settings in the next step!

# --- EMAIL CONFIGURATION ---
# For testing: Prints the email to the terminal instead of actually sending it.
# --- REAL SMTP EMAIL CONFIGURATION ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Replace with the Gmail address you used to generate the password
EMAIL_HOST_USER = 'your.actual.email@gmail.com' 

# Replace with the 16-letter App Password (NO SPACES!)
# IMPORTANT: In a real company, you would put this in a .env file to hide it, 
# but hardcoding it here is fine just to test it right now.
EMAIL_HOST_PASSWORD = 'abcdefghijklmnop' 

DEFAULT_FROM_EMAIL = f'BookMySeat <{EMAIL_HOST_USER}>'

# STRIPE SETTINGS
STRIPE_SECRET_KEY = 'sk_test_51Tm8qqK9yJTnSQDSeFdWopjbLVGfz1oIr9qUivForTcGXkE6Sr0SS5glTlKlqXgWQQllUHESktABIo3sfXqmlLZO00I5umPyYw'
STRIPE_WEBHOOK_SECRET = 'whsec_354b8cca776dae140c56de374f7f6cc7691a036f39a6c5249813a12e2dabbdf4'